name: "Publish to GitHub Pages"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@v19

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build
        run: |
          nix build -L

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result
          cname: jeffreyharmon.dev
          force_orphan: true
          user_name: "github-ci[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: "Publish to gh-pages"
